# -*- coding: utf-8 -*-
"""Week6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YpWQ-o7EMoD_E-IgIPjCRzp4D2HDZ1sb
"""

from google.colab import drive
drive.mount('/content/gdrive')

#task 1_1
import matplotlib.pyplot as plt
from keras.preprocessing.image import load_img

img_path = '/content/gdrive/MyDrive/Assets/Bug1.png'
img = load_img(img_path)


print(type(img))
print(img.format)
print(img.mode)
print(img.size)

plt.imshow(img)
plt.axis('off')
plt.show()

#task 1_2
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import array_to_img

img_path = '/content/gdrive/MyDrive/Assets/Bug2.png'
img = load_img(img_path)
print(type(img))

img_array = img_to_array(img)
print(img_array.dtype)
print(img_array.shape)

img_pil = array_to_img(img_array)
print(type(img))

#task 1_3
import matplotlib.pyplot as plt
import os
from keras.preprocessing.image import load_img
from keras.preprocessing.image import save_img
from keras.preprocessing.image import img_to_array


img_path = '/content/gdrive/MyDrive/Assets/Bug2.png'
img = load_img(img_path, color_mode='grayscale')
img_array = img_to_array(img)

save_path_dir = '/content/gdrive/MyDrive/Assets/'
save_filename = 'Bug2_Greyscale.png'
full_save_path = os.path.join(save_path_dir, save_filename)
save_img(full_save_path, img_array)

img = load_img(full_save_path)
print(type(img))
print(img.format)
print(img.mode)
print(img.size)

plt.imshow(img)
plt.axis('off')
plt.show()

#task 1_4
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()


print('Train', train_images.shape, train_labels.shape)
print('Test', (test_images.shape, test_labels.shape))
# summarize pixel values
print('Train', train_images.min(), train_images.max(), train_images.mean(), train_images.std())
print('Test', test_images.min(), test_images.max(), test_images.mean(), test_images.std())

#task 1_5
from keras.datasets import mnist
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt

(trainX, trainY), (testX, testY) = mnist.load_data()
width, height, channels = trainX.shape[1], trainX.shape[2], 1
trainX = trainX.reshape((trainX.shape[0], width, height, channels))
testX = testX.reshape((testX.shape[0], width, height, channels))

print('Train min=%.3f, max=%.3f' % (trainX.min(), trainX.max()))
print('Test min=%.3f, max=%.3f' % (testX.min(), testX.max()))
datagen = ImageDataGenerator(rescale=1.0/255.0)


train_iterator = datagen.flow(trainX, trainY, batch_size=64)
test_iterator = datagen.flow(testX, testY, batch_size=64)
print('Batches train=%d, test=%d' % (len(train_iterator), len(test_iterator)))

batchX, batchy = next(train_iterator)
print('Batch shape=%s, min=%.3f, max=%.3f' % (batchX.shape, batchX.min(), batchX.max()))

plt.imshow(batchX[0].reshape(28, 28), cmap = 'gray')
plt.axis('off')
plt.show()

plt.imshow(batchX[10].reshape(28, 28), cmap = 'gray')
plt.axis('off')
plt.show()

#task 1_6
from keras.datasets import mnist
from tensorflow.keras.preprocessing.image import ImageDataGenerator

(trainX, trainy), (testX, testy) = mnist.load_data()

width, height, channels = trainX.shape[1], trainX.shape[2], 1
trainX = trainX.reshape((trainX.shape[0], width, height, channels))
testX = testX.reshape((testX.shape[0], width, height, channels))

print('Means train=%.3f, test=%.3f' % (trainX.mean(), testX.mean()))

datagen = ImageDataGenerator(featurewise_center=True)

datagen.fit(trainX)
print('Data Generator Mean: %.3f' % datagen.mean.item())

iterator = datagen.flow(trainX, trainy, batch_size=64)

batchX, batchy = next(iterator)
print(batchX.shape, batchX.mean())

iterator = datagen.flow(trainX, trainy, batch_size=len(trainX), shuffle=False)

batchX, batchy = next(iterator)
print(batchX.shape, batchX.mean())

#task 1_7
from keras.datasets import mnist
from tensorflow.keras.preprocessing.image import ImageDataGenerator

(trainX, trainy), (testX, testy) = mnist.load_data()

width, height, channels = trainX.shape[1], trainX.shape[2], 1
trainX = trainX.reshape((trainX.shape[0], width, height, channels))
testX = testX.reshape((testX.shape[0], width, height, channels))

print('Statistics train=%.3f (%.3f), test=%.3f (%.3f)' % (trainX.mean(), trainX.std(), testX.mean(), testX.std()))

datagen = ImageDataGenerator(featurewise_center=True, featurewise_std_normalization=True)

datagen.fit(trainX)
print('Data Generator mean=%.3f, std=%.3f' % (datagen.mean.item(), datagen.std.item()))

iterator = datagen.flow(trainX, trainy, batch_size=6767)

batchX, batchy = next(iterator)
print(batchX.shape, batchX.mean(), batchX.std())

iterator = datagen.flow(trainX, trainy, batch_size=len(trainX), shuffle=False)
batchX, batchy = next(iterator)
print(batchX.shape, batchX.mean(), batchX.std())